-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 08, 2025 at 06:07 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tour_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `add_city`
--

CREATE TABLE `add_city` (
  `id` int(255) NOT NULL,
  `city_id` int(255) NOT NULL,
  `city_name` varchar(255) NOT NULL,
  `package_type` varchar(255) NOT NULL,
  `price` int(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `heading` text NOT NULL,
  `description` text NOT NULL,
  `image1` varchar(255) NOT NULL,
  `image2` varchar(255) NOT NULL,
  `image3` varchar(255) NOT NULL,
  `location` varchar(255) NOT NULL,
  `image4` varchar(255) NOT NULL,
  `detail1` varchar(255) NOT NULL,
  `detail2` varchar(255) NOT NULL,
  `detail3` varchar(255) NOT NULL,
  `Iterat1` text NOT NULL,
  `Iterat2` text NOT NULL,
  `Iterat3` text NOT NULL,
  `Iterat4` text NOT NULL,
  `Iterat5` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `add_city`
--

INSERT INTO `add_city` (`id`, `city_id`, `city_name`, `package_type`, `price`, `slug`, `heading`, `description`, `image1`, `image2`, `image3`, `location`, `image4`, `detail1`, `detail2`, `detail3`, `Iterat1`, `Iterat2`, `Iterat3`, `Iterat4`, `Iterat5`) VALUES
(1, 1, ' 4 Night/5 Day Bali Tour Package', 'International Trip\r\n', 50000, 'Bali', 'Bali Community Trip', 'Island of the Gods is a breathtaking tropical paradise known for its stunning beaches lush rice terraces and vibrant cultural heritage. Located in Indonesia Bali offers a perfect blend of natural beauty spiritual traditions and modern luxury.Bali, often called the Island of the Gods, is a breathtaking tropical paradise located in Indonesia. Renowned for its stunning beaches, lush rice terraces, and vibrant cultural heritage, Bali offers a perfect blend of natural beauty, spiritual traditions, and modern luxury.<br><br>From the sun-kissed shores of Kuta and Seminyak to the serene, emerald-green landscapes of Ubud’s rice paddies, Bali’s diverse scenery captivates travelers from around the world. The island is also home to majestic temples like Tanah Lot and Uluwatu, where centuries-old architecture meets dramatic coastal views.<br><br>Bali’s cultural richness is reflected in its colorful festivals, traditional dance performances, and exquisite arts and crafts. Visitors can immerse themselves in the local way of life, participate in spiritual ceremonies, or indulge in world-class wellness retreats.', '17408083533014.jpeg', '17398627839899.png', '1739776288.2png', 'Indonesia', '17409826211039.png', 'Ngurah Rai Int\'l Airport to Ngurah Rai Int\'l Airport', 'Backpacking Trips', '4D/5N', '', '', '', '', ''),
(1, 2, '2 Night 3 Days Yogyakarta Tour Package', 'International Trip', 44000, 'welcome to Yogyakarta, Tour', '', 'ava, Indonesia. It is home to the majestic kraton, the royal palace of the sultans, where you can witness traditional ceremonies, performances, and exhibitions. You can also explore the rich collection of the Sonobudoyo Museum, the quirky studio of the famous painter Affandi, and the vibrant street art that decorates the city’s walls.<br><br>For those who crave adventure, Yogya offers breathtaking natural landscapes. Just a short drive away, you’ll find the iconic Mount Merapi, an active volcano where you can take thrilling jeep tours and enjoy stunning sunrise views. Nearby, the Jomblang Cave offers a unique caving experience with its dramatic vertical entrance and mesmerizing beams of light.<br><br>Yogyakarta is also the gateway to two of Indonesia’s most remarkable UNESCO World Heritage sites. The ancient Buddhist temple of Borobudur, with its massive stone stupas and serene surroundings, is a must-see at sunrise. Prambanan, a magnificent Hindu temple complex, showcases intricate stone carvings and a captivating Ramayana ballet performance under the stars.', '17401355623572.png', '17407419229619.png', '1739875434.2png', 'Indonesia', '1739875434.3png', ' Airport to Airport', 'Packages', '3 Days', '', '', '', '', ''),
(1, 3, '1 Day ATV Quad Biking Adventure Tour', 'International Trip', 3000, 'welcome to Indonesia Tour', '', 'Enjoy traveling through local villages and experiencing true Balinese village life whilst passing sacred temples, rice paddies, the jungle, and a 2-design fun track on an exciting ATV adventure. As you ride through the heart of Indonesia’s breathtaking landscapes, you’ll feel the thrill of exploration and the warmth of the local culture.<br><br>This adventure takes you off the beaten path, where you can navigate through lush tropical forests, splash through muddy tracks, and conquer rugged terrains. The scenic beauty around you is simply mesmerizing — towering palm trees, emerald green fields, and traditional Balinese houses create a picturesque backdrop for your journey.<br><br>Along the way, you’ll have opportunities to stop and capture the stunning views, interact with friendly villagers, and learn about their customs and traditions. You’ll pass by ancient temples shrouded in mystique, where you can take a moment to appreciate the spiritual essence of Bali.', '17401219918145.jpg', '1739877513.1png', '1739877513.2png', 'Indonesia', '1739877513.3png', 'Biking Adventure ', 'Packages', '1 Days', '', '', '', '', ''),
(2, 4, ' 2N/D Krabi, 2N/D Phuket', 'International Trip', 29500, 'Thailand Tour', '4 Night 5 Days Thailand tour', 'Indulge in the allure of our Thailand tour package where you embark on a journey to the enchanting realms of Krabi and Phuket, every moment here, is infused with magic and adventure. Nestled along the pristine shores of the Andaman Sea, Krabi captivates with its majestic limestone cliffs and crystal-clear waters, beckoning nature lovers and thrill-seekers alike. The sun-kissed beaches, such as Railay Beach and Ao Nang, offer a serene escape, while the surrounding islands—like Phi Phi Islands and the unspoiled Bamboo Island—promise unforgettable day trips filled with snorkeling, swimming, and exploring hidden caves.\r\n\r\nIn Phuket, the vibrant island comes alive with an abundance of activities. Whether you\'re immersing yourself in the bustling atmosphere of Patong Beach, indulging in world-class dining, or exploring the historic streets of Old Phuket Town, there’s always something to do. For a more tranquil experience, visit the peaceful beaches of Kata and Karon, where you can unwind under the sun or indulge in a luxurious spa treatment overlooking the serene sea.\r\n\r\nAdventure awaits in the lush jungles of Krabi and Phuket, where you can enjoy exhilarating activities like rock climbing, zip-lining, kayaking, and even a day spent exploring the stunning Phang Nga Bay. Whether you\'re trekking through emerald-green forests or embarking on a boat trip to discover secluded coves, your experience in Thailand will be nothing short of spectacular.<br><br>\r\nAfter a day of exploration, indulge in the region’s vibrant culture and rich history, from visiting ancient temples like Wat Tham Sua in Krabi to experiencing the enchanting night markets offering local delicacies and crafts. Let the warm Thai hospitality envelop you, making every step of your journey one to remember.', '1739784391.png', '1739784391.1png', '1739784391.2png', 'Thailand', '1739784391.3png', 'Ngurah Rai Int\'l Airport to Ngurah Rai Int\'l Airport', 'Backpacking Trips', '4 Days', '', '', '', '', ''),
(6, 5, '5 Night 6 Days Nepal Tour Package', 'Internatinoal Trip', 28000, 'Welcome to Nepal', '5 Night 6 Days Nepal Tour Package : Kathmandu, Pokhara', 'Nepal is a beautiful Himalayan country in the South of Asia. It is the land of towering peaks and rich cultural heritage and it is home to the world\'s highest mountain i.e. \'Mount Everest\'. It has everything a traveler seeks–the Himalayas, ancient temples, rich culture, and great food and it is also budget-friendly for Indians.Nepal boasts lush green valleys, serene lakes like Phewa in Pokhara, and picturesque villages that offer a glimpse into its traditional way of life. <br><br>The country’s vibrant festivals, colorful markets, and warm hospitality create an atmosphere of joy and togetherness, while its ancient cities like Kathmandu, Bhaktapur, and Patan showcase stunning architecture and centuries-old craftsmanship. Whether you’re watching a golden sunrise over the Himalayas, hiking through rhododendron forests, or meditating in the peaceful monasteries, Nepal’s beauty lies not just in its landscapes but also in its soul-stirring experiences.', '1739786139.png', '1739786139.1jpg', '1739786139.2jpg', 'Nepal', '1739786139.3jpg', 'Ngurah Rai Int\'l Airport to Ngurah Rai Int\'l Airport', 'Packages', '6 Days ', '', '', '', '', ''),
(6, 6, '4 Night 5 Days Nepal Tour Package', 'Internatinoal Trip', 20000, 'Welcome To Nepal Tour', ' Kathmandu,Pokhara, Manakamana Temple,  Swayambhunath', 'Home to 8 out of 10 highest mountains in the world, the quiet country of Nepal lies in the east of India and shares its borders with 5 Indian states. The country is known for its breathtaking landscapes and rich spiritual heritage, offering an unforgettable journey for travelers seeking both adventure and serenity.<br><br>The country’s diverse geography also offers a wide range of activities — from adrenaline-pumping adventures like paragliding in Pokhara, white-water rafting on the Trishuli River, and wildlife safaris in Chitwan National Park, to more peaceful pursuits like meditation retreats and exploring UNESCO World Heritage sites. Nepal’s warm and welcoming people, vibrant festivals, and traditional arts add to its charm, making every visitor feel at home. Whether you’re marveling at the intricate architecture of ancient stupas, savoring the flavors of authentic Nepali cuisine, or simply soaking in the stunning mountain vistas, Nepal offers an experience that stays with you long after your journey ends.', '17400535475208.png', '1739786671.1jpg', '1739786671.2jpg', 'Nepal', '1739786671.3png', 'Ngurah Rai Int\'l Airport to Ngurah Rai Int\'l Airport', 'Backpacking Trips', '5 Days', '', '', '', '', ''),
(6, 7, '3 Night 4 Days Nepal Tour Package', 'International Trip', 15000, 'Welcome to Nepal Tour', 'Kathmandu sightseeing, chandragiri hills,Bhaleswor Mahadev', 'Nepal is a country located in South Asia bordered by India and China. Nepal is known as the Himalayan Country and it is said that 70% of land in Nepal is covered with Mountains. This Nepal trip package encapsulates the essence of the country in just a few days. Our 3 nights 4 days Nepal package is a beautifully curated itinerary that brings together the highlights of Kathmandu with a scenic escape to the serene Chandragiri Hills.<br><br>you’ll explore the cultural treasures of Kathmandu, including the iconic Pashupatinath Temple, Boudhanath Stupa, and the historic Durbar Square. Stroll through vibrant local markets, marvel at ancient architecture, and soak in the city’s spiritual atmosphere. The adventure continues with a scenic cable car ride to Chandragiri Hills, where you’ll be greeted with panoramic views of the snow-capped Himalayan peaks and lush green landscapes. Whether you’re seeking cultural immersion, breathtaking scenery, or peaceful moments surrounded by nature, this 3-night, 4-day Nepal package promises an unforgettable experience.', '17407410457806.png', '1739787070.1jpg', '17407409324560.jpg', 'Nepal', '1739787070.3jpg', 'Airport to Airport', 'Packages', '4 Days', '', '', '', '', ''),
(7, 8, '3 Night 4 Days Maldives Tour Package', 'International  Trip', 150000, 'welcome to Maldives Tour', ' Dhigufaru Island Resort.', 'This Maldives holiday package allows you to relax in the crystal-clear water of the Indian Ocean. While on a speed boat ride to the resort, you will come across the breathtaking sight of the beautiful blue sea. The stay is absorbed in extreme luxury with the turquoise waters of the ocean surrounding you. To add some flavor to your trip, try and explore the marine life by performing soft adventure activities like snorkeling, surfboarding, basking in the sun at Male Beach, and rejuvenating with an aromatic spa therapy.\r\n<br><br>Make the most of this island paradise by exploring its exotic beaches and unwinding in luxury. Take romantic walks along the pristine white sands, witness mesmerizing sunsets, and indulge in world-class dining experiences by the ocean. For those seeking more adventure, try thrilling water sports like jet skiing, parasailing, and deep-sea diving. Explore the vibrant coral reefs and encounter fascinating marine life up close.<br><br>The Maldives also offers rich cultural experiences — visit the local markets in Male, discover the historic mosques, and learn about the island’s unique traditions. Enjoy a sunset cruise on a traditional Dhoni boat or have a candlelit dinner on a private sandbank for an unforgettable experience.', '17400448226698.jpg', '17400448221908.jpg', '17409873311735.png', 'Maldives', '17400448223467.png', ' Airport to  Airport', 'Packages', '4 Days', '', '', '', '', ''),
(3, 9, '5 Night 6 Days Dubai  Ferrari World Package', 'International Trip', 50000, 'welcome to Dubai Tour', 'Ferrari World', 'Embark on an unforgettable 5-night, 6-day Dubai adventure that perfectly blends futuristic marvels, luxurious escapes, and heart-pounding adventures. Your journey begins with a warm welcome to the City of Gold, setting the stage for an experience like no other. As evening falls, unwind on the magical Marina Dinner Cruise, where glittering cityscapes, mesmerizing belly dance performances, and a delectable buffet offer the perfect introduction to Dubai’s vibrant spirit.<br><br>\r\nDiscover the architectural wonder of the Burj Khalifa, the world’s tallest building, and take in breathtaking panoramic views of the city’s skyline. Wander through the enchanting Dubai Mall, a paradise for shoppers and entertainment enthusiasts alike. Experience the traditional charm of Old Dubai with a visit to the bustling souks, where the aroma of spices and the shimmer of gold create an unforgettable atmosphere.', '17400433598423.png', '17407349376230.png', '17407349372657.png', 'Dubai', '17407349375158.png', ' Airport to Airport', 'Packages', '6 Days', 'Modern Dubai Exploration', 'Cultural Heritage & Old Dubai', 'Desert Safari Adventure', 'Abu Dhabi Day Trip', 'Theme Park or Leisure Day'),
(4, 10, '6 Nights 7 days Bhutan land Tour Package', 'International Trip', 38000, 'Welcome to Bhutan Tour', 'Ex Bagdogra', 'Embark on an extraordinary journey with our meticulously crafted Bhutan travel itinerary, designed to immerse you in the rich heritage and natural beauty of this enchanting destination. Explore iconic landmarks like the majestic Tiger’s Nest Monastery perched on a cliffside, the historic Punakha Dzong, and the bustling markets of Thimphu. Witness the vibrant local festivals, adorned with traditional music, dance, and colorful masks, offering a glimpse into Bhutan’s cultural spirit.<br><br>\r\n\r\nBhutan is a small country nestled in the Himalayas between the Tibet Autonomous Region of China and India. Bhutan offers a myriad of experiences that transcend the ordinary. An extraordinary journey with our meticulously crafted Bhutan travel itinerary, designed to immerse you in the mystical charm of this Himalayan kingdom.Whether you seek spiritual solace, cultural exploration, or thrilling adventures, this thoughtfully curated Bhutan travel experience promises memories that will last a lifetime.\r\n\r\n\r\n\r\n ', '1739793201.png', '1739793201.1jpg', '1739793201.2png', 'Bhutan', '1739793201.3png', 'Airport to Airport', 'Backpacking Trips', '7 Days', '', '', '', '', ''),
(4, 11, '9 Night 10 Days Bhutan Tour Package', 'International Trip', 51000, 'welcome to Bhutan Tour', '', 'Imagine stepping into a world where time slows down and nature’s beauty takes center stage — welcome to Bhutan, the Land of the Thunder Dragon. This magical Himalayan kingdom promises a journey filled with wonder, excitement, and soul-stirring experiences. From the moment you arrive, Bhutan captivates you with its pristine landscapes, rich cultural heritage, and warm hospitality.<br><br>\r\nYour adventure begins in Thimphu, the charming capital where tradition meets modernity. Wander through vibrant markets, marvel at ancient monasteries, and witness the unique blend of old-world charm and contemporary life. As you explore, the excitement builds with each discovery — be it the intricate architecture of Tashichho Dzong or the serene beauty of the Buddha Dordenma statue.<br><br>\r\nThe journey takes you deeper into Bhutan’s heart, where the historic town of Punakha awaits with its stunning riverside fortress and lush valleys. Feel the thrill as you cross the famous suspension bridge, surrounded by fluttering prayer flags and breathtaking views. Every step brings you closer to Bhutan’s soul, and the anticipation of what lies ahead keeps your spirit soaring.', '1739794067.png', '17407385922130.jpg', '17407385928904.png', 'Bhutan', '17407385921707.jpg', 'Bagdogra Airport to Bagdogra Airport', 'Packages', '10 Days', '', '', '', '', ''),
(4, 12, '5 Night and 6 Days Bhutan Road Trip', 'International Trip', 35000, 'welcome to Bhutan Road Trip', '', 'If your heart beats faster at the thought of winding roads, open skies, and breathtaking landscapes — a road trip through Bhutan is calling your name! Experience the thrill of adventure as you drive through scenic mountain passes, lush valleys, and charming villages. Every turn reveals a new surprise — from ancient monasteries perched on cliffs to crystal-clear rivers flowing alongside your journey.<BR><BR>For those seeking an adrenaline rush, Bhutan offers a range of outdoor adventures. Go hiking through pristine trails, camp under starlit skies, or try white-water rafting in the wild, untamed rivers. Whether it’s a bike ride on rugged terrains or a trek to the iconic Tiger’s Nest Monastery, every moment promises excitement and discovery.<br><br>So pack your bags, fuel your wanderlust, and get ready for the adventure of a lifetime!', '17407388748697.png', '17407388749422.png', '17407388748539.jpg', 'Bhutan', '17407388746584.png', 'Bagdogra to Bagdogra', 'Backpacking Trips', '7 Days', '', '', '', '', ''),
(3, 13, '3 Night 4 Days Dubai  Tour Package', 'International Trip', 25500, 'welcome to Dubai Tour', ' Dreams Take Flight', 'Embark on an unforgettable 3-night, 4-day Dubai getaway that perfectly balances modern marvels, luxurious relaxation, and thrilling adventures. From the moment you arrive in the City of Gold, you’ll be swept away by its warm hospitality and dazzling atmosphere. Kick off your journey with a magical evening on the Marina Dinner Cruise, where shimmering skyline views, captivating belly dance performances, and a sumptuous buffet set the perfect tone for the days ahead.<br><br>\r\n\r\nOver the next few days, immerse yourself in Dubai’s extraordinary blend of contemporary wonders and cultural treasures. Stand in awe of the Burj Khalifa’s towering majesty and take in breathtaking views from its observation deck. Explore the vast Dubai Mall, brimming with world-class shopping and entertainment. Stroll through the traditional souks of Old Dubai, where the fragrance of spices and the glint of gold create a timeless charm.', '17400382006860.png', '17400382005283.jpeg', '17407360252849.png', 'Dubai', '17407358949440.png', ' Airport to Airport', 'Packages', '4 Days', 'Desert Safari & Cultural Experience', 'City Tour & Dubai Marina', 'Atlantis Aquaventure & Shopping', ' Burj Khalifa ', 'luxury, adventure, and cultural experiences'),
(3, 14, '5 Night 6 Days Dubai  honeymoon Package', 'International Trip', 50000, 'welcome to Dubai Tour', 'From Desert Sands to Skyscraper Views ', 'Pack-up for the perfect Dubai honeymoon package for 5 days and experience a mix of romance, adventure, and futuristic wonders. This Dubai couple package begins with the Marina Dinner Cruise, where sparkling cityscapes, delicious cuisine, and live performances like the Tanoura Show and Belly Dance set the tone for an unforgettable trip. Explore iconic landmarks like Burj Al Arab, the Palm Jumeirah, and Jumeirah Beach during a vibrant city tour. Top it all off with a mesmerizing evening at the Dubai Mall and the breathtaking views from the 124th floor of Burj Khalifa, the tallest tower in the world.', '17400385064512.png', '17400385062522.jpeg', '17400385064712.png', 'Dubai', '17400385069060.png', ' Airport to Airport', 'Packages', '6 Days', 'Dubai City Exploration', 'Desert Safari & Cultural Experience', ' Dubai Creek & Old Dubai', ' Jumeirah Beach & Budget Shopping', 'Global Village & Dubai Marina'),
(3, 15, '4 Night 5 Days Dubai  Honeymoon Package', 'International Trip', 45000, 'welcome to Dubai Tour', 'Love as endless as the desert sands.', 'Pack your bags for the ultimate Dubai honeymoon package — a 5-day journey filled with romance, adventure, and futuristic wonders. From the moment you arrive in the City of Gold, love and excitement fill the air. <br><br>\r\nExplore Dubai’s most iconic landmarks on a vibrant city tour, visiting architectural marvels like the sail-shaped Burj Al Arab, the luxurious Palm Jumeirah, and the sun-kissed sands of Jumeirah Beach. Stroll hand in hand through the sprawling Dubai Mall, where shopping and entertainment meet in perfect harmony. ', '17407378695889.png', '17407378697063.png', '17407375112939.png', 'Dubai', '17407375116601.png', ' Airport to Airport', 'Honeymoon Package', '5  Days', '', '', '', '', ''),
(7, 16, '4 Night 5 Days Maldives Honeymoon Package', 'International  Trip', 94500, 'welcome to Maldives Tour', 'Two hearts, one paradise ', 'Maldives has always been a destination chosen by honeymooners. This 4-night Maldives honeymoon package will let you soak yourself in extreme natural beauty. Located at South Malé Atoll, the Sun Siyam Olhuveli will offer all the luxuries you can imagine. Enjoy the balmy breeze and the blues of the Indian Ocean while you romanticize at the white sand beaches. Hit the waves with some adventure activities if you feel like, or indulge in a detoxifying spa. Enjoy the delicious breakfast, lunch, dinner, and unlimited selected beverages throughout your stay.<br><br>\r\nWake up to breathtaking views of the ocean from your water villa, and start your day with a floating breakfast in your private pool. Spend your afternoons exploring the vibrant marine life with snorkeling or diving excursions, and take a sunset cruise on a traditional Maldivian dhoni. In the evenings, savor candlelight dinners by the beach and unwind with live music or cultural performances.<br><br>\r\nFor couples seeking relaxation and rejuvenation, the resort’s world-class spa offers a variety of treatments inspired by ancient wellness traditions. If adventure calls, try windsurfing, kayaking, or jet skiing on the crystal-clear waters.', '17400437328868.jpg', '17400437326551.jpg', '17409876044503.png', 'Maldives', '17400437326995.jpg', ' Airport to  Airport', 'Honeymoon Package', '5 Days', '', '', '', '', ''),
(7, 17, '3 Night 4 Days Maldives Tour Package', 'International  Trip', 90000, 'welcome to Maldives Tour', 'A love as beautiful as the Maldives, serene and endless.', 'Maldives has always been a destination chosen by honeymooners. This 3-night Maldives honeymoon package will let you soak yourself in extreme natural beauty. Located at South Malé Atoll, the Sun Siyam Olhuveli will offer all the luxuries you can imagine. Enjoy the balmy breeze and the blues of the Indian Ocean while you romanticize at the white sand beaches. Hit the waves with some adventure activities, if you feel like, or have a detox spa. Enjoy the delicious breakfast, lunch, dinner, and unlimited chosen beverages throughout your stay.\r\n\r\nYour overwater villa offers breathtaking views of crystal-clear lagoons and stunning sunsets right from your private deck. Spend your days lounging by the infinity pool, snorkeling among vibrant coral reefs, or setting sail on a romantic sunset cruise. For thrill-seekers, there’s windsurfing, jet skiing, and diving excursions guided by certified instructors.<br><br>\r\nWhen it’s time to unwind, indulge in world-class spa treatments at the overwater sanctuary or take a leisurely walk along the moonlit beach. The resort also offers private candlelit dinners under the stars, adding a touch of magic to your evenings.', '17400479629958.png', '17400479622336.jpg', '17409877507651.png', 'Maldives', '17400479626293.jpg', ' Airport to  Airport', 'Packages', '4 Days', '', '', '', '', ''),
(5, 18, '5 Night 6 Days Russia Tour Package', 'International Trip', 104226, 'welcome to Moscow', 'The Moscow Kremlin', 'A Journey Through History and Beauty Get ready to explore one of the world’s most fascinating cities—Moscow, where history and grandeur come alive. At the very heart of this stunning metropolis stands the Kremlin, the largest active fortress in Europe. Originally built to protect Moscow’s citizens, the very word ‘Kremlin’ translates to ‘fortress inside a city’. Over the centuries, as Russia’s influence grew, the Moscow Kremlin became a powerful symbol of authority and elegance. Walking through its storied walls, you’ll feel the echoes of the past blending seamlessly with the present.<br><br>\r\nJust steps away lies the world-famous Red Square, a breathtakingly beautiful space whose name originates from the word ‘Krasnaya’, meaning both ‘red’ and ‘beautiful’ in Old Russian. With its striking architecture and vibrant atmosphere, the Red Square truly lives up to its name. As you stand amidst its iconic landmarks, you’ll be captivated by the colors, the history, and the undeniable charm that make this square one of the most beloved places in the world.', '1739948228.jpg', '17407398945573.png', '1739948228.2png', 'Russia', '1739948228.3jpeg', 'Airport to Airport', 'Backpacking Trips', '6 Days   ', '', '', '', '', ''),
(5, 19, '5 Nights 6 days Russia Honeymoon Package', 'International Trip', 107000, 'welcome to Russia', 'A Love Story in the Land of Snow & Stars', 'Embark on an unforgettable journey of love where romance meets grandeur in the heart of Russia. From the fairytale charm of Moscow’s twinkling skyline to the poetic canals of Saint Petersburg, every moment of your honeymoon will be wrapped in elegance, passion, and adventure.\r\n\r\nStart your journey in Moscow, a city where history and modernity blend seamlessly. Stroll hand in hand through the iconic Red Square, illuminated beautifully at night, and marvel at the colorful domes of St. Basil’s Cathedral. Take a private tour of the majestic Kremlin, where tales of power and beauty unfold. As the sun sets, enjoy a candlelit dinner with panoramic views of the Moscow River, creating memories you’ll cherish forever.<br><br>Next, board a luxurious train to the cultural gem of Saint Petersburg. Known as the Venice of the North, this city offers endless opportunities for romance. Glide along the Neva River on an enchanting boat ride, passing beneath charming bridges and beside opulent palaces. Explore the world-renowned Hermitage Museum, home to breathtaking art collections housed in the stunning Winter Palace. Wander through the lush gardens of Peterhof, often called the Russian Versailles, where fountains dance in harmony with nature.', '17401347093610.png', '1739949649.1png', '1739949649.2png', 'Russia', '1739949649.3png', 'Airport to Airport', 'Honeymoon Package', '6 Days   ', '', '', '', '', ''),
(5, 20, '4 Night 5 Days Russia Tour package', 'International Trip', 59000, 'welcome to Russia', '', ' The St. Basil’s Cathedral (located at Red Square) and Christ the Saviour Cathedral to name a few. Other than the same there are a number of most content and composed sightseeing places like Sparrow Hills.The St. Basil’s Cathedral (located at Red Square) and Christ the Saviour Cathedral, to name a few, are iconic symbols of Moscow’s rich history and stunning architecture. <br><br>Other than these, there are a number of serene and composed sightseeing places like Sparrow Hills, offering panoramic views of the city and a perfect spot for quiet reflection and romantic walks. Gorky Park, with its beautiful landscapes and lively ambiance, also invites couples to enjoy leisurely strolls and outdoor activities.<br><br>architectural marvels, there are a number of serene and composed sightseeing places like Sparrow Hills, offering panoramic views of the city and a perfect spot for quiet reflection and romantic walks. Gorky Park, with its beautiful landscapes and lively ambiance, also invites couples to enjoy leisurely strolls and outdoor activities.', '17401346817576.png', '1739951452.1png', '1739951452.2png', 'Russia', '1739951452.3png', 'Airport to Airport', 'Package', '5 Days   ', '', '', '', '', ''),
(5, 21, '3 Night 4 Days Russia Honeymoon Package', 'International  Trip', 52411, 'welcome to Russia Tour', ' Dhigufaru Island Resort.', 'Moscow, the heart and soul of Russia, is a city where history, culture, and romance intertwine seamlessly. This vibrant capital offers an enchanting mix of ancient landmarks and modern sophistication, making it the perfect destination for a love-filled getaway. Stroll through its wide boulevards, marvel at its opulent architecture, and immerse yourselves in its rich heritage.\r\n\r\nThe St. Basil’s Cathedral, located at the iconic Red Square, stands as a symbol of Moscow’s rich history and unique beauty. Its colorful onion-shaped domes and whimsical design make it one of the most photographed and admired landmarks in the world. As you walk around this architectural masterpiece, you’ll be captivated by its fairytale-like appearance and the stories that echo through its walls. Nearby, the Christ the Saviour Cathedral impresses with its grandeur and spiritual significance, offering a peaceful retreat and a stunning backdrop for romantic moments.<br><br>Other than these architectural marvels, there are a number of serene and composed sightseeing places like Sparrow Hills, offering panoramic views of the city and a perfect spot for quiet reflection and romantic walks. Gorky Park, with its beautiful landscapes and lively ambiance, also invites couples to enjoy leisurely strolls and outdoor activities.', '1739959855.jpeg', '1739959855.1png', '1739959855.2png', 'Russia', '17407405471547.jpg', ' Airport to  Airport', 'Packages', '4 Days', '', '', '', '', ''),
(8, 22, '9 Night 10 Days Philippnes Tour Package', 'International  Trip', 204000, 'welcome to Philippnes Tour', 'A Paradise of Islands', 'A trip to the Philippines is nothing short of magical — a perfect blend of relaxation, adventure, and awe-inspiring beauty. Imagine starting your journey in Boracay, where the soft, powdery sands of White Beach meet the clear turquoise waters. Spend your days soaking up the sun, enjoying water sports like parasailing and paddleboarding, and experiencing vibrant nightlife by the beach.\r\n\r\nNext, fly to Palawan and take a boat tour through El Nido’s dramatic limestone cliffs and hidden lagoons. Swim in crystal-clear waters, snorkel among colorful coral reefs, and kayak through secret caves. In Coron, dive into the famous Kayangan Lake, surrounded by towering cliffs and some of the clearest water you’ll ever see.\r\n\r\nFor a change of scenery, head to Bohol and visit the unique Chocolate Hills — rolling, grass-covered mounds that turn brown in the dry season. Take a river cruise on the Loboc River, where you’ll enjoy local food and live music as you float through lush greenery. Don’t miss a visit to Panglao Island’s beaches for more stunning coastline and excellent diving spots.<br><br>\r\nIf you’re feeling adventurous, trek up the terraces of Banaue or hike to the summit of Mount Pulag to witness a breathtaking sea of clouds at sunrise. For a laid-back vibe, explore the island of Siargao, famous for its world-class surfing, rock pools, and laid-back atmosphere.', '1739956979.png', '17409879189774.png', '17409878859175.png', 'Philippines', '1739956979.3png', ' Airport to  Airport', 'Packages', '10 Days', '', '', '', '', ''),
(8, 24, '5 Night 6 Days philippines Honeymoon Package', 'International  Trip', 68300, 'welcome to Philippines Tour', '', 'The capital city of Manila is a blend of modern skyscrapers and historic landmarks. Visit Intramuros, Rizal Park, and explore the vibrant street markets for a taste of Filipino culture. As you wander through the streets of Intramuros, the walled city, you’ll be transported back to the Spanish colonial era. Cobblestone streets, centuries-old churches like San Agustin Church, and Fort Santiago tell stories of the city’s rich history and resilience.<BR>BR>\r\nRizal Park, or Luneta Park, is a sprawling green space dedicated to the national hero, Dr. Jose Rizal. It’s a perfect spot for relaxation, family picnics, and cultural appreciation, with monuments, gardens, and historical markers scattered throughout. The nearby National Museum Complex offers a deeper dive into the country’s art, history, and natural heritage.\r\n\r\nFor a more contemporary experience, head to the bustling districts of Makati and Bonifacio Global City (BGC). These areas showcase Manila’s modern face with gleaming skyscrapers, high-end shopping centers, and a vibrant nightlife. The shopping malls like Greenbelt, Glorietta, and SM Aura are not just retail hubs—they also feature world-class dining and entertainment options.', '1739960737.png', '1739960737.1png', '1739960737.2png', 'Philippines', '17409881693775.png', ' Airport to  Airport', ' Adventure Packages', '6 Days', '', '', '', '', ''),
(8, 25, '5 Night 6 Days philippines Honeymoon Package', 'International  Trip', 120000, 'welcome to Philippines Tour', 'A Honeymoon to Remember ', 'Begin your journey of love amidst the breathtaking beauty of the Philippines — a paradise where sun-kissed beaches, crystal-clear waters, and enchanting landscapes set the perfect stage for your honeymoon.\r\n\r\nImagine walking hand-in-hand along the powdery white sands of Boracay, watching the golden sunset paint the sky.', '1739962066.png', '1739962066.1png', '1739962066.2png', 'Philippines', '1739962066.3png', ' Airport to  Airport', 'Honeymoon Package', '6 Days', '', '', '', '', ''),
(9, 26, '9 Night 10 Days Egypt Tour Package', 'International  Trip', 168887, 'welcome to Egypt Tour', 'An Unforgettable Egyptian Adventure', 'Embark on a journey through time as you explore the wonders of Cairo and the Nile River. Experience the perfect blend of history, culture, and luxury as you visit the iconic pyramids and sail through ancient temples along the legendary Nile.\r\n\r\nYour adventure begins in Cairo, a bustling metropolis where modernity meets antiquity. Start your day at the awe-inspiring Giza Plateau, home to the Great Pyramids and the Sphinx — timeless monuments that have stood for over 4,000 years. Walk in the footsteps of pharaohs, marvel at the engineering genius of these ancient structures, and capture stunning photos against the backdrop of the desert.<BR><BR>\r\nNext, immerse yourself in the rich history of the Egyptian Museum, where countless artifacts, including the treasures of King Tutankhamun, tell the stories of a fascinating civilization. Wander through the vibrant Khan El Khalili bazaar, where the scent of spices and the shimmer of handcrafted goods create an unforgettable atmosphere.', '1739963074.png', '1739963074.1png', '17409883869900.png', 'Egypt', '17409883462521.png', ' Airport to  Airport', 'Packages', '10 Days', '', '', '', '', ''),
(9, 27, '9 Night 10 Days Egypt  Honeymoon Package', 'International  Trip', 290000, 'welcome to Egypt Tour', 'A Romantic & Cultural Getaway', 'Begin your journey of love amidst the breathtaking beauty of Malaysia — a paradise where sun-kissed beaches, crystal-clear waters, and enchanting landscapes set the perfect stage for your honeymoon. Imagine walking hand-in-hand along the powdery white sands of Langkawi, watching the golden sunset paint the sky with hues of orange and pink. The gentle sound of waves whispers sweet melodies as you create unforgettable memories with your loved one.<br><br>\r\n\r\nVenture into the lush, green tea plantations of Cameron Highlands, where the rolling hills offer a serene and picturesque escape. Take a boat ride through the stunning limestone caves of the Batu Caves, exploring hidden wonders and cultural landmarks that feel like your own private paradise. For adventurous couples, Malaysia offers thrilling activities like diving in the vibrant coral reefs of Sipadan, hiking up the majestic peaks of Mount Kinabalu, or exploring the lush rainforests of Taman Negara. If relaxation is your desire, indulge in luxurious beachfront resorts and spa retreats that cater to your every need', '1739964229.png', '1739964229.1png', '1739964229.2png', 'Egypt', '1739964229.3png', ' Airport to  Airport', 'Honeymoon Package', '10 Days', '', '', '', '', ''),
(11, 28, '3 Night 4 Days Paris Tour Package', 'International  Trip', 67700, 'welcome to Paris Tour', '', 'Though your first trip to Paris is going to be all about the Eiffel Tower, there is a lot in this city of love that you need to explore. The Paris tour packages make sure that you don’t miss any of the must-visit places, giving you the easiest way to explore the town. Right from museum-touring to operas to the shopping, Paris is sure to keep you entertained throughout your stay.Though your first trip to Paris is going to be all about the Eiffel Tower, there is a lot in this city of love that you need to explore. The Paris tour packages make sure that you don’t miss any of the must-visit places, giving you the easiest way to explore the town. Right from museum-touring to operas to shopping, Paris is sure to keep you entertained throughout your stay, with its charming cafés, stunning architecture, and vibrant street life. Whether you’re strolling along the Seine, marveling at the art in the Louvre, or indulging in delicious French cuisine, every corner of Paris offers a new adventure and unforgettable memories.\r\n\r\nOne of the first stops on your Paris tour should be the iconic Eiffel Tower. Standing tall against the Parisian skyline, it offers breathtaking views of the city, especially at sunset. Take a leisurely walk around Champ de Mars or enjoy a romantic dinner at one of the tower’s restaurants. But Paris is not just about the Eiffel Tower — it has much more in store. The Louvre Museum is a must-visit for art lovers. Home to the famous Mona Lisa and thousands of other priceless artworks, the museum offers a journey through history and creativity.<br><br>For those who enjoy exploring history and architecture, the Notre-Dame Cathedral is a perfect stop. Despite the tragic fire in 2019, the cathedr', '17401350522145.png', '1739965136.1png', '1739965136.2png', 'Paris', '1739965136.3png', ' Airport to  Airport', 'Packages', '4 Days', '', '', '', '', ''),
(11, 29, '2 Night 3 Days  Paris Honeymoon Package', 'International  Trip', 43900, 'welcome to Paris Tour', 'Romantic Paris Honeymoon Tour', 'Experience the magic of Paris, the City of Love, on a dreamy honeymoon getaway. From iconic landmarks to charming streets and world-class cuisine, this tour is designed to create unforgettable memories with your loved one.Experience the magic of Paris, the City of Love, on a dreamy honeymoon getaway. From iconic landmarks to charming streets and world-class cuisine, this tour is designed to create unforgettable memories with your loved one.<br><br>\r\nStroll hand-in-hand along the Seine River as you take in the enchanting views of the Eiffel Tower, glowing beautifully against the evening sky. Wander through the cobbled streets of Montmartre, where artists capture the romance of the city on their canvases, and enjoy a quiet moment at the charming Sacré-Cœur Basilica. Indulge in Paris’s renowned culinary scene, from cozy cafés serving buttery croissants to Michelin-starred restaurants offering exquisite French cuisine. Share a candlelit dinner with your partner while savoring fine wine and decadent desserts.', '1739966522.png', '1739966522.1png', '1739966522.2png', 'Paris', '1739966522.3png', ' Airport to  Airport', 'Honeymoon Packages', '3 Days', '', '', '', '', ''),
(12, 30, '6 Night 7 Days Greece Tour Package', 'International  Trip', 149244, 'welcome to Greece Tour', 'Lost in the beauty of Greece, found in each other\'s arms', 'Greece is a breathtaking destination where ancient history, stunning landscapes, and vibrant culture come together in perfect harmony. From the iconic ruins of Athens, like the Acropolis, to the pristine beaches of the Aegean and Ionian Seas, every corner of Greece offers something magical. Explore the charming white-washed buildings and crystal-clear waters of the Greek Islands, such as Santorini and Mykonos, or indulge in delicious Mediterranean cuisine in quaint coastal villages. Wander through the cobblestone streets of Rhodes, where medieval architecture whispers tales of the past, or marvel at the majestic monasteries perched atop the towering rock formations of Meteora. For nature lovers, Greece offers breathtaking hiking trails through the Samaria Gorge in Crete or the lush greenery of Mount Pelion.\r\n<br><br>\r\nThe country’s rich mythology comes alive at historic sites like Delphi and Olympia, while vibrant cities like Thessaloniki blend ancient charm with a modern, lively atmosphere. Don’t miss the chance to experience traditional Greek hospitality — whether you’re savoring fresh seafood by the sea, enjoying lively music and dance at a local taverna, or simply relaxing under the Mediterranean sun.\r\n\r\nEvery region of Greece offers its own unique flavor, from the olive groves of Kalamata to the wine regions of Nemea. Whether you seek adventure, history, relaxation, or cultural immersion, Greece promises an unforgettable journey filled with beauty, warmth, and wonder.', '17401354287996.png', '1740049423.1png', '1740049423.2png', 'Greece', '1740049423.3png', ' Airport to  Airport', 'Honeymoon Packages', '7 Days', '', '', '', '', ''),
(12, 31, '4 Night 5 Days Greece Tour Package', 'International  Trip', 87124, 'welcome to Greece Tour', 'A journey through Greece, where love and history collide.', 'Greece is a dream come true, a land where love and beauty intertwine at every turn. Picture walking hand in hand through ancient ruins, gazing at the timeless splendor of the Acropolis as the sun sets over the Mediterranean. The charming cobbled streets of the Greek Islands, with their whitewashed homes and blooming bougainvillaea, feel like a perfect escape. In Greece, the deep blue waters of the Aegean invite you to relax, while the rich history whispers stories of the past. Whether you\'re savoring a romantic dinner overlooking the sea or sailing through crystal-clear waters, Greece is a place where every moment feels like a celebration of love and life.\r\nImagine waking up to the gentle sound of waves and the soft glow of sunrise casting golden light over Santorini’s iconic blue-domed churches. Spend your days exploring hidden beaches, swimming in turquoise waters, and wandering through picturesque villages where every corner feels like a postcard.\r\n<BR><BR>\r\nAs evening falls, indulge in a candlelit dinner on a cliffside terrace, tasting fresh Mediterranean flavors and sipping fine Greek wine while the sun dips below the horizon in a blaze of colors. Take a sunset cruise around Mykonos or Rhodes, where the reflection of the sky dances on the water, creating a magical atmosphere that feels tailor-made for romance.\r\n\r\nFor those seeking adventure, hike the scenic trails of Crete or explore ancient sites like Delphi and Olympia, where history and mythology come alive. Or simply lose yourselves in the charm of small seaside towns, where locals greet you with warmth and every moment feels relaxed and timeless.', '17401353067940.png', '1740050012.1png', '17409927436911.png', 'Greece', '1740050012.3png', ' Airport to  Airport', 'Packages', '5 Days', '', '', '', '', ''),
(12, 32, '3 Night 4 Days Greece Honeymoon Package', 'International  Trip', 123500, 'welcome to Greece Tour', 'Santorini Gateway!', 'Begin your journey of love amidst the breathtaking beauty of the Philippines — a paradise where sun-kissed beaches, crystal-clear waters, and enchanting landscapes set the perfect stage for your honeymoon.\r\n<br><br>\r\nImagine walking hand-in-hand along the powdery white sands of Boracay, watching the golden sunset paint the sky.with hues of orange, pink, and violet. Feel the gentle sea breeze as it whispers sweet nothings, and let the soothing sound of waves create a symphony of romance.\r\nVenture into the lush, green terraces of Banaue, where nature’s artistry offers a serene escape from the world. Explore the captivating lagoons and hidden coves of Palawan, where every turn reveals a scene straight out of a dream. Snorkel or dive together in the vibrant coral gardens of Cebu, discovering an underwater wonderland that mirrors the beauty of your love.\r\n\r\nIndulge in intimate candlelit dinners by the beach, with the freshest seafood and the sound of the ocean as your backdrop. Pamper yourselves with luxurious spa treatments, or set off on exciting adventures like island hopping, kayaking, and hiking.', '1740051389.png', '1740051389.1png', '1740051389.2png', 'Greece', '17409924528377.png', ' Airport to  Airport', 'Honeymoon Packages', '4 Days', '', '', '', '', ''),
(10, 33, '8 Night 9 Days Malaysia  Package', 'International  Trip', 87800, 'welcome to Malaysia Tour', 'A Tour to Remember ', 'Begin your journey of love amidst the breathtaking beauty of Malaysia — a paradise where sun-kissed beaches, crystal-clear waters, and enchanting landscapes set the perfect stage for your honeymoon. Imagine walking hand-in-hand along the powdery white sands of Langkawi, watching the golden sunset paint the sky with hues of orange and pink. The gentle sound of waves whispers sweet melodies as you create unforgettable memories with your loved one.\r\n<br><br>\r\nVenture into the lush, green tea plantations of Cameron Highlands, where the rolling hills offer a serene and picturesque escape. Take a boat ride through the stunning limestone caves of the Batu Caves, exploring hidden wonders and cultural landmarks that feel like your own private paradise. For adventurous couples, Malaysia offers thrilling activities like diving in the vibrant coral reefs of Sipadan, hiking up the majestic peaks of Mount Kinabalu, or exploring the lush rainforests of Taman Negara. If relaxation is your desire, indulge in luxurious beachfront resorts and spa retreats that cater to your every need', '1740051951.png', '1740051951.1png', '17400520514092.png', 'Malaysia', '1740051951.3png', ' Airport to  Airport', ' Packages', '9 Days', '', '', '', '', ''),
(10, 34, '4 Night 5 Days Malaysia  Package', 'International  Trip', 30500, 'welcome to Malaysia Tour', 'A Kuala Lumpur Special Honeymoon to Remember ', 'Embark on a romantic journey through Malaysia, blending vibrant city life, stunning beaches, and scenic beauty into an unforgettable experience. This 7-day, 6-night honeymoon package takes you to the best destinations, including the bustling metropolis of Kuala Lumpur, the tropical paradise of Langkawi, and the charming, cultural vibes of Penang.his carefully curated honeymoon package offers a perfect balance of relaxation, adventure, and cultural exploration.<br><br>\r\nStart your journey in Kuala Lumpur, where the city’s iconic skyline, world-class shopping, and delicious cuisine await. Visit the majestic Petronas Towers, explore the lively streets of Bukit Bintang, and immerse yourselves in the city’s vibrant nightlife. Take a romantic evening stroll at KLCC Park, or enjoy a candlelit dinner with breathtaking views.\r\n\r\nNext, fly to Langkawi, a haven of crystal-clear waters and lush greenery. Indulge in luxurious beachfront resorts, take a sunset cruise, or explore the island’s natural wonders like the Langkawi Sky Bridge and the Seven Wells Waterfall. For thrill-seekers, there’s snorkeling, parasailing, and jungle trekking.\r\n\r\nConclude your journey in Penang, known for its historic charm and rich culture. Wander through the colorful streets of George Town, a UNESCO World Heritage site, with its stunning street art and colonial architecture. Savor local delicacies at the famous hawker stalls and unwind on the serene beaches of Batu Ferringhi.\r\n\r\n\r\n\r\nImagine walking hand-in-hand along the powdery white sands of Boracay, watching the golden sunset paint the sky.', '17400531591509.png', '17400531593762.png', '17409921289887.png', 'Malaysia', '1740053106.3png', ' Airport to  Airport', ' Honeymoon Packages', '5 Days', '', '', '', '', ''),
(3, 35, '5 Night 6 Days Community Trip', 'internationa;', 56000, 'Welcome to Dubai Community Trip', '', 'Dubai is a vibrant and cosmopolitan city located in the United Arab Emirates (UAE), known for its grandeur, innovation, and modernity. Nestled along the southeast coast of the Arabian Gulf, this city has transformed from a humble fishing village into a global metropolis and a major hub for business, tourism, and luxury. With its towering skyscrapers, extravagant shopping malls, pristine beaches, and rich cultural heritage, Dubai offers a unique blend of traditional Arabian charm and contemporary allure. In the community trip to Dubai we will cover the best of Dubai in 6 Days. JustWarvel\'s Group Tour to Dubai is specially designed to make sure that you get the perfect sip of luxury and fun. This dazzling city in the UAE, is a perfect blend of modernity and tradition. Its highlights include the iconic Burj Khalifa, the luxurious Palm Jumeirah, the sprawling Dubai Mall, and the opulent Burj Al Arab which we are covering in our Dubai group tour. \r\n\r\n', '1741004507.png', '17410801053431.png', '17410801051093.jpg', 'Dubai', '17410801054865.png', 'Dubai Int\'l Airport to Dubai Int\'l Airport ', 'Backpacking Trip', '6 Days', '', '', '', '', '');
INSERT INTO `add_city` (`id`, `city_id`, `city_name`, `package_type`, `price`, `slug`, `heading`, `description`, `image1`, `image2`, `image3`, `location`, `image4`, `detail1`, `detail2`, `detail3`, `Iterat1`, `Iterat2`, `Iterat3`, `Iterat4`, `Iterat5`) VALUES
(2, 36, '5 Night 6 Days Thailand Trip', 'International Trip', 25000, 'Welcome toThailand Trip', '', 'Embark on an unforgettable journey through our Thailand tour package with a captivating 5-day Thailand itinerary, where adventure, relaxation, and cultural discovery await at every turn. Your adventure begins in Phuket, Thailand\'s largest island, where a dynamic blend of culture, nightlife, and natural beauty awaits. Settle into your accommodation and prepare to immerse yourself in the wonders of this enchanting destination. The next day, embark on a thrilling Phi Phi Island tour, where you\'ll explore the breathtaking beauty of these iconic islands by a speedboat. Let our experienced guides lead you to marvel at the wonders of Maya Bay, Viking Cave, and Monkey Beach, surrounded by stunning limestone cliffs and crystal-clear waters teeming with vibrant marine life. <br><br>\r\n\r\n \r\n\r\nThe excitement continues with a full-day James Bond Island tour, where you\'ll board a speedboat and journey to Khao Ping Khan, famously known as James Bond Island. As you cruise through Phang Nga Bay, marvel at the dramatic scenery and explore enchanting mangrove forests. Enjoy kayaking around Hong Island before indulging in a delicious lunch on Panyee Island. Relax on the serene shores of Naka Noi Island, soaking in the beauty of your surroundings. As your adventure in Phuket unfolds, take a step back in time with a Phuket City Tour, where you\'ll explore the island\'s rich cultural heritage. ', '1741080394.png', '1741080394.1png', '1741080394.2png', 'Thailand', '1741080394.3jpg', 'Phuket International Airport to Phuket International Airport', 'Packages', '6 Days', '', '', '', '', ''),
(2, 37, '8 Night 9 Days Thailand Tour ', 'Internatiional Trip', 400000, 'Welcome to Thailand  Trip', '', 'Commence on a magnificent Thai journey that seamlessly combines the unique charms of Pattaya, the dynamic energy of Bangkok, the tropical paradise of Phuket, and the natural beauty of Krabi. Get ready for an adventure of a lifetime! \r\nPattaya provides the ideal blend of relaxation and excitement. From there, your adventure continues to the bustling heart of Thailand, Bangkok. This metropolis harmoniously combines ancient traditions with modern marvels. Explore iconic temples like Wat Pho and Wat Arun, cruise along the Chao Phraya River, and savor the vibrant markets and delicious street food. Bangkok\'s nightlife is legendary, featuring rooftop bars, night markets, and cultural performances that will captivate you. Your next destination is the tropical island paradise of Phuket. <br><br>\r\nSurrounded by crystal-clear waters, Phuket boasts world-class beaches such as Patong, Kata, and Karon. Enjoy sun-filled days, water adventures, snorkeling, and diving to explore the rich underwater world. Discover the island\'s cultural heritage in Old Phuket Town and savor exquisite Thai cuisine. Whether you\'re seeking relaxation or adventure, Phuket offers it all. Conclude your Thai adventure in the natural beauty of Krabi. ', '1741080980.png', '17410863121457.png', '1741080980.2png', 'Thailand', '1741080980.3png', 'Phuket International Airport to Phuket International Airport', 'Packages', '9 Days', '', '', '', '', ''),
(5, 38, '6 Night 7 Days Russia Tour Package', 'International Trip', 145000, 'Welcome to Russia Trip', '', 'mbark on an unforgettable journey through Russia, a country rich in history, culture, and breathtaking landscapes. From the majestic architecture of Moscow’s Red Square to the artistic treasures of St. Petersburg, Russia offers a perfect blend of tradition and modernity.\r\nExplore iconic landmarks like the Kremlin, St. Basil’s Cathedral, and the Hermitage Museum. Cruise along the scenic rivers, experience the famous Trans-Siberian Railway, and immerse yourself in the local charm of quaint villages and vibrant cities.<br><br>\r\nWhether you want to witness the Northern Lights in Murmansk, ski in the Caucasus Mountains, or relax by the serene Lake Baikal, Russia has something for every traveler.', '17410860025666.png', '1741081745.1png', '17410860703236.png', 'Russia', '1741081745.3png', 'Airport to  Airport', 'Packages', '7 Days', '', '', '', '', ''),
(9, 39, '7 Night 8 Days Egypt Tour Packages', 'International Trip', 60000, 'Welcome to Egypt Trip', '', 'Embark on the Pharaohs Nile Cruise Adventure — a journey through the heart of ancient Egypt, where history and luxury blend seamlessly. As you sail down the majestic Nile River, you’ll witness breathtaking landscapes, timeless monuments, and the vibrant culture of Egypt.\r\n\r\nYour adventure begins in Cairo, the bustling capital, where you’ll explore the Great Pyramids of Giza and the enigmatic Sphinx. After soaking in the grandeur of these world wonders, you’ll board a luxurious cruise ship, your home for the next few days.<br><br>\r\nGlide along the lifeline of Egypt, stopping at iconic destinations like Luxor and Aswan. In Luxor, marvel at the Karnak Temple and the Valley of the Kings, where ancient pharaohs rest in elaborately decorated tombs. In Aswan, visit the picturesque Philae Temple and take a serene felucca ride on the Nile.\r\n\r\nThroughout the cruise, you’ll enjoy world-class amenities, including comfortable cabins with stunning river views, gourmet dining, and entertainment inspired by Egyptian traditions. Engage in cultural activities, relax on the sun deck, or unwind with a spa treatment.\r\n\r\nAs the sun sets over the Nile, you’ll experience the magic of Egypt’s golden sands and historic marvels, creating memories that last a lifetime. The Pharaohs Nile Cruise Adventure is not just a trip — it’s a voyage through time, where every moment tells a story of splendor and mystery.', '1741082543.png', '1741082543.1png', '1741082543.2jpg', 'Egypt', '1741082543.3png', 'Airport to  Airport', 'Packages', '8 Days', '', '', '', '', ''),
(11, 40, '5 Night 6 Days Paris Trip Package', 'International Trip', 95629, 'Welcome to Paris  Trip', '', 'Explore the magic of Paris with our exclusive package priced at just ₹95,626 per package. This specially curated trip offers a perfect blend of elegance, romance, and adventure in the City of Lights. Enjoy a luxurious 5-night, 6-day stay in the heart of Paris with daily breakfast and dinner included. Discover iconic landmarks like the Eiffel Tower, Louvre Museum, Notre-Dame Cathedral, and the Champs-Élysées through guided tours.<br><br> Experience a mesmerizing evening cruise along the scenic Seine River and take advantage of comfortable airport transfers and local transport. With ample time for shopping and leisure at chic boutiques and vibrant streets, this package ensures an authentic and unforgettable Parisian experience. In addition to these incredible highlights, you’ll also get the opportunity to indulge in Paris’s world-renowned cuisine, explore charming neighborhoods like Montmartre and Le Marais, and capture picture-perfect moments at Trocadéro Gardens. Whether you’re strolling along the romantic Seine, marveling at the city’s architectural wonders, or enjoying a coffee at a quaint sidewalk café, every moment in Paris promises to be extraordinary. Book your Paris adventure today and create memories that will last a lifetime!\r\n\r\n', '1741083069.png', '1741083069.1png', '1741083069.2png', 'Paris', '1741083069.3png', 'Airport to  Airport', 'Packages', '6 Days', '', '', '', '', ''),
(10, 41, '5 Night 6 Days Malaysia Tour Package', 'International Trip', 80000, 'Welcome to Malaysia  Trip', '', 'Embark on an unforgettable journey to Malaysia — a destination where adventure, culture, and relaxation come together in perfect harmony. Our carefully curated travel packages offer the best of this Southeast Asian paradise, whether you’re drawn to bustling cities, serene beaches, or breathtaking natural landscapes.\r\n\r\nExplore Kuala Lumpur, Malaysia’s vibrant capital, where iconic landmarks like the Petronas Twin Towers meet lively street markets and mouthwatering local cuisine. Experience the awe of the Batu Caves and enjoy world-class shopping in modern malls and traditional bazaars.\r\n\r\nFor beach lovers, Langkawi awaits with its crystal-clear waters and luxurious resorts. Dive into thrilling water sports, ride the famous cable car for panoramic views, or unwind on pristine sandy beaches. Penang, the \'Pearl of the Orient,\' offers colonial charm, stunning street art, and some of the world’s best street food.<br><br>\r\n\r\nNature enthusiasts will love the lush Cameron Highlands, perfect for exploring tea plantations and scenic hiking trails. If you crave a wilder adventure, head to Borneo’s rainforests to encounter orangutans and exotic wildlife in their natural habitat.', '1741083738.png', '1741083738.1jpg', '1741083738.2png', 'Malaysia', '1741083738.3png', 'Airport to  Airport', 'Packages', '6 Days', '', '', '', '', '');

-- --------------------------------------------------------

--
-- Table structure for table `add_country`
--

CREATE TABLE `add_country` (
  `id` int(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `Type_of_trip` text NOT NULL,
  `heading` varchar(255) NOT NULL,
  `image` varchar(500) NOT NULL,
  `location` varchar(500) NOT NULL,
  `explore_image` varchar(500) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `meta_description` varchar(1500) NOT NULL,
  `price` int(255) NOT NULL,
  `creation_date` date NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `add_country`
--

INSERT INTO `add_country` (`id`, `name`, `Type_of_trip`, `heading`, `image`, `location`, `explore_image`, `slug`, `meta_description`, `price`, `creation_date`) VALUES
(1, ' Beautiful Islands and Beaches', 'Inetrnational Trip', ' Beautiful Islands And Beaches', '1739525759.png', 'Indonesia', '17401170521.jpg', 'welcome to indonesia', ' Indonesia is  known for its rich culture, diverse landscapes, and unique traditions. With a mix of modern cities, ancient temples, lush rainforests and stunning beaches, Indonesia offers something for every traveler. Indonesia, the world’s largest archipelago, is a breathtaking destination that offers travelers an unparalleled mix of adventure, culture, and natural beauty. <br><br>\r\nOne of Indonesia’s most famous destinations is Bali, often called the \"Island of the Gods.\" This world-renowned paradise is known for its stunning beaches, vibrant culture, and lush landscapes. Picture yourself watching a mesmerizing sunset from the iconic Tanah Lot temple or exploring the artistic streets of Ubud, known for its traditional dance performances, crafts, and serene rice terraces.\r\n<br><br>\r\nBeyond Bali, Indonesia boasts countless other gems. Jakarta, the bustling capital, offers a blend of modern skyscrapers and historic sites like the Kota Tua (Old Town) with its charming colonial architectu', 30000, '2025-02-14'),
(2, 'Every sunrise is a promise of new adventures.', 'International Trip', 'Land of Tropical Paradise', '1739525904.png', 'Thailand', '17401170931.png', 'Welcome To Thailand Tour', 'Thailand is a vibrant Southeast Asian country known for its rich history, tropical beaches, bustling cities, and mouthwatering cuisine. It offers the perfect mix of culture, adventure, and relaxation, making it one of the top travel destinations in the world Whether you want to explore ancient temples, unwind on pristine beaches, or immerse yourself in the vibrant nightlife, Thailand has something for everyone.. <br><br>\r\n\r\nStart your journey in Bangkok, the capital city that never sleeps. A dynamic blend of tradition and modernity, Bangkok is home to dazzling skyscrapers, bustling street markets, and centuries-old temples. The magnificent Grand Palace and Wat Phra Kaew (Temple of the Emerald Buddha) are must-visit landmarks that showcase Thailand’s royal history. Take a boat ride along the Chao Phraya River, explore the vibrant streets of Chinatown, or enjoy the electric atmosphere of Khao San Road, where travelers from all over the world come to experience the city’s legendary nightl', 29000, '2025-02-14'),
(3, 'The City of Dreams and Luxury', 'International Trip', 'The City of Dreams and Luxury', '1740122859.png', 'Dubai', '17401171421.png', ' Welcome to Dubai', 'Dubai is a city that seamlessly blends the futuristic with the traditional, offering a unique travel experience like no other. Known for its towering skyscrapers, luxurious shopping, pristine beaches, and rich cultural heritage, Dubai is a destination that caters to every type of traveler. Whether you’re looking for adventure, relaxation, or world-class entertainment, Dubai has it all.<br><br>\r\n\r\nYour journey begins in Downtown Dubai, where the iconic Burj Khalifa, the world’s tallest building, stands as a symbol of modern innovation. Ascend to the observation deck on the 148th floor and enjoy panoramic views of the city’s sprawling skyline, the Arabian Desert, and the shimmering waters of the Persian Gulf. Below, the Dubai Fountain dances to music and lights, offering a mesmerizing spectacle that will leave you in awe.<br><br>\r\n\r\nDubai’s shopping scene is legendary. The Dubai Mall, one of the largest shopping centers in the world, offers more than just retail therapy. From high-end boutiques to an indoor ice rink, an aquarium, and a virtual reality park, the mall is an entertainment hub in itself. For a more traditional shopping experience, visit the souks of Dubai, where you can haggle for spices, gold, textiles, and perfumes, capturing the essence of Arabian culture.<br><br>\r\n\r\nFor those seeking adventure, Dubai delivers thrills like no other. Take a desert safari and experience the excitement of dune bashing, a ride over the golden sand dunes in a 4x4. Afterward, you can ', 25500, '2025-02-14'),
(4, 'The Land of Thunder Dragons', 'International Trip', 'The Land Of Happiness', '1739526192.png', 'Bhutan', '17401171901.jpg', 'welcome to Bhutan Tour', 'Bhutan, a serene and mystical kingdom nestled in the heart of the Himalayas between the Tibet Autonomous Region of China and India, offers an experience unlike any other. Known for its breathtaking landscapes, vibrant culture, and the philosophy of Gross National Happiness, Bhutan is a haven for travelers seeking tranquility and adventure alike.<br><br>Embark on an extraordinary journey with our meticulously crafted Bhutan travel itinerary, designed to immerse you in the rich heritage and natural beauty of this enchanting destination. Explore iconic landmarks like the majestic Tiger’s Nest Monastery perched on a cliffside, the historic Punakha Dzong, and the bustling markets of Thimphu. Witness the vibrant local festivals, adorned with traditional music, dance, and colorful masks, offering a glimpse into Bhutan’s cultural spirit.<br><br>For nature enthusiasts, Bhutan’s lush valleys, crystal-clear rivers, and towering mountains provide endless opportunities for hiking, wildlife spotting', 35000, '2025-02-14'),
(5, ' Tradition and Technology Shapes the Future!', 'International Trip', 'The Land of  Timeless Beauty', '1740134618.png', 'Russia', '17401346181.png', 'Russia', 'Russia is a land of incredible diversity, rich history, and breathtaking landscapes. Stretching across two continents and 11 time zones, it is the largest country in the world, offering a stunning mix of ancient traditions and modern innovations. From the icy tundra of Siberia to the vibrant streets of Moscow, Russia is a destination that captivates travelers with its grandeur, culture, and mystery.<br><br>\r\n\r\nStart your journey in Moscow, the beating heart of Russia, where history and modernity coexist in a mesmerizing blend. The Kremlin, a fortress of golden-domed cathedrals and government buildings, stands as a symbol of Russian power and heritage. Just outside, Red Square unfolds its magnificent sights, including the iconic.\r\n<br><br> St. Basil’s Cathedral, with its colorful onion-shaped domes that look like something from a fairytale. The nearby Bolshoi Theatre hosts world-class ballet and opera performances, while the luxurious shopping street of Tverskaya showcases Russia’s conteemporary fashion and culture. As you stroll through the streets of Moscow, you’ll encounter a harmonious blend of old-world charm and cutting-edge design, with historic churches and modern skyscrapers standing side by side. Don’t miss a visit to the Moscow Metro, often regarded as the most beautiful subway system in the world, with its ornate stations that reflect the country’s rich architectural heritage.\r\n\r\nBeyond Moscow, Russia’s vast landscapes offer a myriad of adventures. Travel to the se', 52400, '2025-02-14'),
(6, 'A land where the Himalayas touch the sky, spirituality fills the air', 'Inetrnational Trip', ' The Mountains Whisper Ancient Tales', '1739526038.png', 'Nepal', '17401177451.jpg', 'Welcome To Nepal Tour', ' Nepal is home to the majestic Himalayas including Mount Everest the world highest peak. Nepal is a federal democratic republic with diverse ethnic groups languages and traditions. It is famous for its deep spiritual roots ancient temples and adventurous spirit making it a paradise for travelers seeking both serenity and excitement. Nestled between China and India Nepal is a land of stunning landscapes rich cultural heritage and warm hospitality.<br><br> Whether you are a thrill-seeker eager to conquer the world highest peaks or a spiritual explorer looking to immerse yourself in centuries-old traditions Nepal offers an unforgettable journey.\r\n\r\nThe most iconic attraction in Nepal is without a doubt Mount Everest towering at 8848 meters. Everest is a dream destination for mountaineers from around the globe. Even for those who do not aim to reach the summit the Everest Base Camp Trek offers breathtaking views of snow-capped peaks charming Sherpa villages and a glimpse into the lives o', 15000, '2025-02-14'),
(7, ' The epitome of paradise , pristine beaches.', 'International Trip', ' The Epitome Of Paradise , Pristine Beaches.', '1739517213.jpg', 'Maldives', '17401177781.jpg', ' Welcome to Maldives', 'The Maldives is the epitome of paradise, with its beautiful islands and pristine beaches. Known for its crystal-clear turquoise waters, powder-soft white sand, and vibrant coral reefs, the Maldives offers a breathtaking escape into nature’s most serene and luxurious settings. Whether you seek relaxation, romance, adventure, or a mix of all three, this tropical paradise is a dream destination for every traveler.\r\n<br><br>\r\nImagine waking up in an overwater villa, where the gentle sound of waves greets you, and stepping out onto your private deck to witness a sunrise that paints the sky in shades of gold and pink. The Maldives is home to some of the world most exclusive resorts, each offering unparalleled luxury and hospitality. From Malé, the lively capital, to remote private islands, every corner of the Maldives promises an unforgettable experience.\r\n', 25000, '2025-02-14'),
(8, 'Unleash the Adventure, Feel the Magic!', 'International Trip', 'Unleash the Adventure, Feel the Magic!', '1739517460.png', 'Philipines', '17401178611.png', 'welcome to Philipines Tour', 'The Philippines is a tropical paradise full of life and adventure. With over seven thousand islands it offers breathtaking beaches, stunning landscapes and rich cultural heritage. From the crystal-clear waters of Palawan to the vibrant streets of Manila , the Philippines has something for every traveler. From the vibrant streets of Manila to the hidden lagoons of Palawan, every corner of the country offers a unique and unforgettable experience.\r\n<br><br>\r\nOne of the Philippines’ biggest draws is its world-famous beaches and islands. Boracay, with its powder-soft sand and electric nightlife, is a favorite for those looking to relax and celebrate by the sea. For those seeking untouched beauty, El Nido and Coron in Palawan boast dramatic limestone cliffs, turquoise waters, and hidden lagoons, perfect for island hopping and snorkeling. Siargao, known as the surfing capital of the country, offers thrilling waves, breathtaking rock pools, and a laid-back island vibe. For underwater explorers', 68250, '2025-02-14'),
(9, 'Land of Pharaohs, Timeless Wonders!', 'International Trip', 'The Pyramids Stand As Timeless Witnesses .', '1739517776.png', 'Egypt', '17401179001.png', ' Welcome to Egypt', 'Egypt is a land of wonders where history, mystery, and romance intertwine to create an unforgettable journey. Home to the majestic pyramids, the mighty Nile River, and ancient temples, this enchanting country holds the secrets of one of the world’s greatest civilizations. From the golden sands of the Sahara to the vibrant streets of Cairo, every corner of Egypt tells a story of passion, power, and timeless beauty. Whether you’re seeking a romantic escape under starlit skies or a thrilling adventure through ancient ruins, Egypt promises an experience like no other.\r\n<br><br>\r\nImagine sailing down the Nile River at sunset, the water reflecting the warm hues of the setting sun while you drift past temples that have stood for thousands of years. A cruise along this legendary river is nothing short of magical, taking you to some of Egypt’s most breathtaking sites, including the Luxor and Karnak Temples, where towering pillars and intricate carvings whisper tales of pharaohs and gods. ', 60000, '2025-02-14'),
(10, 'A Land of Diversity, Adventure, and Charm', 'International Trip', 'A Land of Diversity, Adventure, and Charm', '1739526714.jpeg', 'Malaysia', '17401179281.png', ' welcome to Malaysia', 'Malaysia is a vibrant destination where modern cities, lush rainforests, and pristine beaches come together to create an unforgettable experience. From the iconic Petronas Towers in Kuala Lumpur, standing tall against the skyline, to the breathtaking islands of Langkawi, where crystal-clear waters kiss white sandy shores, Malaysia is a land of endless wonders. Every corner of this beautiful country offers something unique, from adventurous escapes to cultural discoveries, making it a must-visit destination for travelers seeking both excitement and relaxation.\r\n<br><br>\r\nKuala Lumpur, the bustling capital, is a mesmerizing blend of futuristic skyscrapers and traditional charm. Walk through the lively streets of Bukit Bintang, where neon lights, luxurious malls, and street food stalls create an electric atmosphere. Visit the Petronas Twin Towers, the pride of Malaysia, where you can enjoy panoramic views of the city from the sky bridge. For a touch of nature within the city.', 30000, '2025-02-14'),
(11, 'A Land of Elegance Beauty and Timeless Charm', 'International Trip', 'Love In France Is Like A Fine Perfume', '1740134960.png', 'France', '17401349601.png', 'France', 'France is the ultimate destination for romance, where every corner is steeped in beauty, history, and charm. From the timeless elegance of Paris to the sun-kissed shores of the French Riviera, love lingers in the air. Strolling hand in hand along the Seine River, gazing at the shimmering Eiffel Tower, or getting lost in the artistic streets of Montmartre, Paris offers endless moments of enchantment. For a dreamlike escape, the lavender fields of Provence paint the landscape in shades of purple, filling the air with a sweet fragrance that feels like poetry in motion. The French Riviera, with its glamorous cities like Nice, Cannes, and Monaco, invites couples to bask in the golden sunsets by the Mediterranean, sip fine wine at seaside cafés, and explore charming villages perched on cliffs overlooking the sea. <br><br>The fairytale castles of Loire Valley, the vineyards of Bordeaux, and the snow-covered peaks of the French Alps offer unique backdrops for romance in every season.For advent', 43000, '2025-02-14'),
(12, ' A Land of Myth History and Endless Beauty', 'International Trip', ' A Land of Myth History and Endless Beauty', '1739520074.png', 'Greece', '17401179831.png', ' welcome to Greece', 'Greece is a land of myth, beauty, and timeless charm, where ancient ruins stand proudly alongside the deep blue waters of the Aegean. It is a country that blends history, culture, and breathtaking landscapes, making it a dream destination for travelers. From the majestic Acropolis in Athens, which tells the story of Greece’s glorious past, to the white-washed villages of Santorini, where sunsets paint the sky in hues of gold and pink, every corner of Greece offers something extraordinary.<br><br>\r\n\r\nFor those enchanted by history, Delphi, once considered the center of the world in ancient Greek mythology, offers a glimpse into the past with its mysterious ruins and stunning mountain backdrop. Meteora, with its breathtaking rock formations and centuries-old monasteries perched atop towering cliffs, feels like a place suspended between heaven and earth. In Crete, the legendary Palace of Knossos takes visitors on a journey back to the Minoan civilization, the oldest in Europe', 87000, '2025-02-14');

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `email` varchar(500) NOT NULL,
  `password` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `email`, `password`) VALUES
(1, 'sharma81amrita@gmail.com', 'Lovetheflow@9');

-- --------------------------------------------------------

--
-- Table structure for table `booking`
--

CREATE TABLE `booking` (
  `id` int(255) NOT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(10) DEFAULT NULL,
  `package` varchar(255) DEFAULT NULL,
  `price` int(255) NOT NULL,
  `quantity` int(11) DEFAULT NULL,
  `total_amount` decimal(11,0) DEFAULT NULL,
  `booking_date` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  `payment_status` varchar(255) DEFAULT NULL,
  `payment_id` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `booking`
--

INSERT INTO `booking` (`id`, `first_name`, `last_name`, `email`, `phone`, `package`, `price`, `quantity`, `total_amount`, `booking_date`, `payment_status`, `payment_id`) VALUES
(1, 'priya ', 'chaudhary', 'priya@gmail.com', '2147483647', '5 Night 6 Days Thailand Trip', 25000, 1, 26250, NULL, NULL, 'pay_QCWn7yYaQq724G'),
(2, 'rupal', 'singh', 'rupal@gmail.com', '2147483647', '5 Night 6 Days Thailand Trip', 25000, 1, 26250, '2025-03-29 07:43:06', NULL, 'pay_QCWYamgMfY3W9Q');

-- --------------------------------------------------------

--
-- Table structure for table `registration`
--

CREATE TABLE `registration` (
  `id` int(255) NOT NULL,
  `name` text NOT NULL,
  `phone` int(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `registration`
--

INSERT INTO `registration` (`id`, `name`, `phone`, `email`, `city`, `password`) VALUES
(1, 'Priya chaudhary', 2147483647, 'priya@gmail.com', 'greater noida', 'life123'),
(2, 'rupal', 2147483647, 'rupal@gmail.com', 'noida', 'life123'),
(3, 'AMRITA', 2147483647, 'sharma81amrita@gmail.com', 'DDN', 'LIFE123'),
(4, 'deepa', 2147483647, 'deepa@gmail.com', 'delhi', 'bnm123');

-- --------------------------------------------------------

--
-- Table structure for table `tour_packages`
--

CREATE TABLE `tour_packages` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `duration` varchar(100) DEFAULT NULL,
  `price` int(11) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tour_packages`
--

INSERT INTO `tour_packages` (`id`, `name`, `location`, `duration`, `price`, `image`) VALUES
(1, 'Mesmerizing Maldives Escape', 'Maldives', '4 Nights / 5 Days', 30000, 'img/maldives.jpg'),
(2, 'Captivating Qatar Adventure ', 'Qatar', '5 Nights / 6 Days', 12000, 'img/qatar/qatar-temple.jpg'),
(3, 'Exotic Thailand Tour', 'Thailand', '6 Nights / 7 Days', 25000, 'img/thailand.jpg'),
(4, 'Nepal’s Peaks & Serenity Tour', 'Nepal', '4 Nights / 5 Days', 15000, 'img/nepal/boudhanath-stupa-kathmandu-nepal.png'),
(5, 'Dubai Luxury Escape', 'Dubai', '5 Nights / 6 Days', 200000, 'img/dubai.jpg'),
(6, 'European Delight Tour', 'Europe', '10 Nights / 11 Days', 200000, 'img/europe.jpg'),
(7, 'Sun, Sand & Smiles Experience ', 'Philipines', '4 Nights / 5 Days', 10000, 'img/Philipines/Philipines-sea.png'),
(8, 'Golden Temples & Azure Seas', 'Thailand', '5 Nights / 6 Days', 15000, 'img/thailand/landmark-wat-thai-with-shadow-re.png'),
(9, 'Mysteries of Ancient Egypt', 'Egypt', '6 Nights / 7 Days', 15000, 'img/egypt/sphinx-against-backdrop-great-eg.png'),
(10, 'Explore Europe in budget', 'Europe', '6 Nights / 7 Days', 85000, 'img/Seine River Cruise.jpeg'),
(11, 'Explore Dubai in Budget', 'Dubai', '5 Nights / 6 Days', 39000, 'img/dubai/Burj Khalifa.jpeg'),
(12, 'Amazing Dubai Tour', 'Dubai', '4 Nights / 5 Days', 78000, 'img/dubai/jumeirah.jpeg\r\n');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `add_city`
--
ALTER TABLE `add_city`
  ADD PRIMARY KEY (`city_id`);

--
-- Indexes for table `add_country`
--
ALTER TABLE `add_country`
  ADD PRIMARY KEY (`id`) USING BTREE;

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `booking`
--
ALTER TABLE `booking`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `registration`
--
ALTER TABLE `registration`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tour_packages`
--
ALTER TABLE `tour_packages`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `add_city`
--
ALTER TABLE `add_city`
  MODIFY `city_id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT for table `add_country`
--
ALTER TABLE `add_country`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `booking`
--
ALTER TABLE `booking`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `registration`
--
ALTER TABLE `registration`
  MODIFY `id` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `tour_packages`
--
ALTER TABLE `tour_packages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
